# Generated by Django 5.1.6 on 2025-03-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_contact_owner_mailings_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "permissions": [("can_view_contact", "Can_view_contact")],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
        migrations.AlterModelOptions(
            name="mailings",
            options={
                "ordering": ["status"],
                "permissions": [
                    ("can_is_active_mailings", "Can_is_active_mailings"),
                    ("can_view_mailings", "Can_view_mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_message", "Can_view_message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
    ]
